### PR TITLE
#3 fix - allow multiple files in input. globs parsed by shell, not argparse.

### PR DESCRIPTION
**Pull request by pit**

### CODE REVIEW

**Comment by pit** [comment]
#3 fix

**Comment by pit** [comment]
inplace file editing added #2

**Comment by elijahchancey** [comment]
It looks like basic -i functionality works. If I run pretty_cloudformation.py -i *.yml I get output that looks like this:
```
$ ~/git/pit/pretty_cloudformation/pretty_cloudformation.py -i *.yml








Traceback (most recent call last):
  File "/Users/elijahchancey/git/pit/pretty_cloudformation/pretty_cloudformation.py", line 47, in <module>
    data = yaml.safe_load(data)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/Users/elijahchancey/git/pit/pretty_cloudformation/pretty_cloudformation.py", line 35, in default_constructor
    raise NotImplementedError('Node: ' + str(type(node)))
NotImplementedError: Node: <class 'yaml.nodes.SequenceNode'>
```
It looks like every file that is processed generates a newline character. Could you add functionality that says: `Processing: filename.yml`? That would make more sense than just outputting a newline character.

I'm pretty sure the `NotImplementedError: Node: <class 'yaml.nodes.SequenceNode'>` error is occurring because of issue #1 

Thanks!

**Comment by pit** [comment]
As for #1 issue - yes, it's not implemented yet so will be fixed later. Made this PR to see/check intermediate results.

>Could you add functionality that says: Processing: filename.yml
sure, no problem, easy

**Comment by pit** [comment]
As for new line after each file - it's only printed to stdout, to to file. Just to separate processed files when dumping to stdout

**Comment by elijahchancey** [comment]
I'm seeing a lot of extra output. Can you silence the Loader messages? Thanks!

```
Processing: file.yml
Loader:<yaml.loader.SafeLoader object at 0x1030014e0>, tag_suffic:!ImportValue, node:ScalarNode(tag='!ImportValue', value='VpcId')
```

**Comment by pit** [comment]
done

**Comment by elijahchancey** [comment]
Everything looks great. Thanks!

**Pull request merged**
